/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAddressValidityTemporary } from "./IAddressValidityTemporary";
export * as factories from "./factories";
export { IAddressValidityTemporary__factory } from "./factories/IAddressValidityTemporary__factory";
