/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPaymentTemporary } from "./IPaymentTemporary";
export * as factories from "./factories";
export { IPaymentTemporary__factory } from "./factories/IPaymentTemporary__factory";
