/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IPayment {
  export type RequestBodyStruct = {
    transactionId: BytesLike;
    inUtxo: BigNumberish;
    utxo: BigNumberish;
  };

  export type RequestBodyStructOutput = [
    transactionId: string,
    inUtxo: bigint,
    utxo: bigint
  ] & { transactionId: string; inUtxo: bigint; utxo: bigint };

  export type ResponseBodyStruct = {
    blockNumber: BigNumberish;
    blockTimestamp: BigNumberish;
    sourceAddressHash: BytesLike;
    receivingAddressHash: BytesLike;
    intendedReceivingAddressHash: BytesLike;
    spentAmount: BigNumberish;
    intendedSpentAmount: BigNumberish;
    receivedAmount: BigNumberish;
    intendedReceivedAmount: BigNumberish;
    standardPaymentReference: BytesLike;
    oneToOne: boolean;
    status: BigNumberish;
  };

  export type ResponseBodyStructOutput = [
    blockNumber: bigint,
    blockTimestamp: bigint,
    sourceAddressHash: string,
    receivingAddressHash: string,
    intendedReceivingAddressHash: string,
    spentAmount: bigint,
    intendedSpentAmount: bigint,
    receivedAmount: bigint,
    intendedReceivedAmount: bigint,
    standardPaymentReference: string,
    oneToOne: boolean,
    status: bigint
  ] & {
    blockNumber: bigint;
    blockTimestamp: bigint;
    sourceAddressHash: string;
    receivingAddressHash: string;
    intendedReceivingAddressHash: string;
    spentAmount: bigint;
    intendedSpentAmount: bigint;
    receivedAmount: bigint;
    intendedReceivedAmount: bigint;
    standardPaymentReference: string;
    oneToOne: boolean;
    status: bigint;
  };

  export type ResponseStruct = {
    attestationType: BytesLike;
    sourceId: BytesLike;
    votingRound: BigNumberish;
    lowestUsedTimestamp: BigNumberish;
    requestBody: IPayment.RequestBodyStruct;
    responseBody: IPayment.ResponseBodyStruct;
  };

  export type ResponseStructOutput = [
    attestationType: string,
    sourceId: string,
    votingRound: bigint,
    lowestUsedTimestamp: bigint,
    requestBody: IPayment.RequestBodyStructOutput,
    responseBody: IPayment.ResponseBodyStructOutput
  ] & {
    attestationType: string;
    sourceId: string;
    votingRound: bigint;
    lowestUsedTimestamp: bigint;
    requestBody: IPayment.RequestBodyStructOutput;
    responseBody: IPayment.ResponseBodyStructOutput;
  };

  export type ProofStruct = {
    merkleProof: BytesLike[];
    data: IPayment.ResponseStruct;
  };

  export type ProofStructOutput = [
    merkleProof: string[],
    data: IPayment.ResponseStructOutput
  ] & { merkleProof: string[]; data: IPayment.ResponseStructOutput };

  export type RequestStruct = {
    attestationType: BytesLike;
    sourceId: BytesLike;
    messageIntegrityCode: BytesLike;
    requestBody: IPayment.RequestBodyStruct;
  };

  export type RequestStructOutput = [
    attestationType: string,
    sourceId: string,
    messageIntegrityCode: string,
    requestBody: IPayment.RequestBodyStructOutput
  ] & {
    attestationType: string;
    sourceId: string;
    messageIntegrityCode: string;
    requestBody: IPayment.RequestBodyStructOutput;
  };
}

export interface PaymentTemporaryInterface extends Interface {
  getFunction(
    nameOrSignature: "proof" | "request" | "response"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "proof",
    values: [IPayment.ProofStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "request",
    values: [IPayment.RequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "response",
    values: [IPayment.ResponseStruct]
  ): string;

  decodeFunctionResult(functionFragment: "proof", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "request", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "response", data: BytesLike): Result;
}

export interface PaymentTemporary extends BaseContract {
  connect(runner?: ContractRunner | null): PaymentTemporary;
  waitForDeployment(): Promise<this>;

  interface: PaymentTemporaryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  proof: TypedContractMethod<[_proof: IPayment.ProofStruct], [void], "view">;

  request: TypedContractMethod<
    [_request: IPayment.RequestStruct],
    [void],
    "view"
  >;

  response: TypedContractMethod<
    [_response: IPayment.ResponseStruct],
    [void],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "proof"
  ): TypedContractMethod<[_proof: IPayment.ProofStruct], [void], "view">;
  getFunction(
    nameOrSignature: "request"
  ): TypedContractMethod<[_request: IPayment.RequestStruct], [void], "view">;
  getFunction(
    nameOrSignature: "response"
  ): TypedContractMethod<[_response: IPayment.ResponseStruct], [void], "view">;

  filters: {};
}
